name: table_calendar
description: Highly customizable, feature-packed Flutter Calendar with gestures, animations and multiple formats.
version: 2.0.1
author: Aleksander Woźniak <aleksanderwozniak96@gmail.com>
homepage: https://github.com/aleksanderwozniak/table_calendar

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  intl: 
  simple_gesture_detector:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
